packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
  msw: false
  prisma: true
  "@prisma/client": true
  "@prisma/engines": true
  better-auth: true
  better-auth-studio: true
